src/models/__init__.py
__author__ = 'hooper-p'

src/__init__.py
__author__ = 'hooper-p'

src/app.py
from src.models.attendance.attendance import Attendance
from src.models.players.player import Player

__author__ = 'hooper-p'

from flask import Flask, render_template
from src.common.database import Database


from src.models.games.game import Game

from src.models.attendance.views import attendance_blueprint

app = Flask(__name__)
app.config.from_object('src.config')
app.secret_key = '123'

app.register_blueprint(attendance_blueprint, url_prefix='/attendance')


@app.before_first_request
def init_db():
    Database.initialize()


@app.route('/')
def home():
    # Player.update_players()
    Attendance.update_games()
    # Attendance.build_first()
    # return render_template('base.html')
    games = Game.get_games()
    for a in Attendance.get_all_attendance():
        a.save_to_mongo()

    return render_template('home.html', games=games)

src/common/__init__.py
__author__ = 'hooper-p'

src/models/attendance/__init__.py
__author__ = 'hooper-p'

src/models/attendance/views.py
from flask import Blueprint, render_template, request

from src.models.attendance.attendance import Attendance

__author__ = 'hooper-p'

attendance_blueprint = Blueprint('attendance', __name__)


@attendance_blueprint.route('/<string:game_id>', methods=['GET', 'POST'])
def view_game(game_id):
    if request.method == 'POST':
        attendance = Attendance.get_attendance_by_game(game_id)
        for a in attendance:
            a.attendance = request.form['attendance' + str(a._id)]
            if a._id == request.form['beverages']:
                a.beverages = 'Yes'
            else:
                a.beverages = 'No'
            a.save_to_mongo()

    attendance = Attendance.get_attendance_by_game(game_id)
    how_many = Attendance.yes_attendance_by_game(game_id)
    return render_template("attendance/game_attendance.html", attendance=attendance, how_many=len(how_many))

src/models/games/__init__.py
__author__ = 'hooper-p'

src/models/players/__init__.py
__author__ = 'hooper-p'

src/templates/__init__.py
__author__ = 'hooper-p'

src/templates/attendance/__init__.py
__author__ = 'hooper-p'

src/templates/attendance/game_attendance.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <a class="btn btn-primary" href="{{ url_for('home') }}" role="button"><< Back to Schedule</a>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row justify-content-center">
        <img src="{{ url_for('static', filename='images/Rolling_Rock_logo.gif') }}"
             style="max-width:200px; max-height:200px; margin-top: -7px; margin-bottom: 10px">
    </div>
    <hr>
    <div class="row">
        <div class="col text-center">
            <h1>Attendance for Game on {{ attendance[0].game.date }}</h1>
            <h5><strong>{{ how_many }}</strong> people have said they are coming to the game</h5>
        </div>
    </div>
    <form method="post">
        <div class="row header justify-content-center text-center ">
            <div class="col">
                <button class='btn btn-outline-success btn-lg mx-auto' name='save' type='submit'><i
                        class="fa fa-floppy-o" aria-hidden="true"></i> Save changes
                </button>
            </div>
        </div>
        <div class="row">
            &nbsp;
        </div>
        <div class="row header justify-content-center text-center ">
            <div class="col-1 col-md-1"><strong>Number</strong></div>
            <div class="col-5 col-md-3"><strong>Name</strong></div>
            <div class="col-4 col-md-2"><strong>Yes/No</strong></div>
            <div class="col-1 col-md-1"><strong>Beers?</strong></div>
        </div>
        <input type="radio" name="beverages" value="None" style="opacity: 0;" checked>
        {% for a in attendance %}
        <div class="row detail text-center justify-content-center">
            <div class="col-2 col-md-1">{{ a.player.number }}</div>
            <div class="col-5 col-md-3">{{ a.player.name }}</div>
            <div class="col-4 col-md-2">
                <div class="btn-group" data-toggle="buttons">
                    <label class="btn btn-primary {% if a.attendance == 'Yes' %}active{% endif %}">
                        {% if a.attendance == 'Yes' %}
                        <input type="radio" name="attendance{{ a._id }}" id="yes" value="Yes" autocomplete="off"
                               checked>Yes
                        {% else %}
                        <input type="radio" name="attendance{{ a._id }}" id="yes" value="Yes" autocomplete="off">Yes
                        {% endif %}
                    </label>
                    <label class="btn btn-primary {% if a.attendance == 'Und' %}active{% endif %}">
                        {% if a.attendance == 'Und' %}
                        <input type="radio" name="attendance{{ a._id }}" id="und" value="Und" autocomplete="off"
                               checked>--
                        {% else %}
                        <input type="radio" name="attendance{{ a._id }}" id="und" value="Und" autocomplete="off">--
                        {% endif %}
                    </label>
                    <label class="btn btn-primary {% if a.attendance == 'No' %}active{% endif %}">
                        {% if a.attendance == 'No' %}
                        <input type="radio" name="attendance{{ a._id }}" id="no" value="No" autocomplete="off"
                               checked>No
                        {% else %}
                        <input type="radio" name="attendance{{ a._id }}" id="no" value="No" autocomplete="off">No
                        {% endif %}
                    </label>
                </div>
            </div>

            <div class="col-1 col-md-1 form-check">
                <label class="form-check-label">
                    {% if a.beverages == 'Yes' %}
                    <input class="form-check-input" type="radio" name="beverages" id="beverages{{ a._id }}"
                           value="{{ a._id }}" checked>
                    {% else %}
                    <input class="form-check-input" type="radio" name="beverages" id="beverages{{ a._id }}"
                           value="{{ a._id }}">
                    {% endif %}
                </label>
            </div>
        </div>
        {% endfor %}

        <div class="row header justify-content-center text-center ">
            <div class="col">
                <button class='btn btn-outline-success btn-lg mx-auto' name='save' type='submit'><i
                        class="fa fa-floppy-o" aria-hidden="true"></i> Save changes
                </button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Richmond Couch Potatoes</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" media="screen" href="{{ url_for('static', filename='css/main.css') }}">

    <style>
     @media screen and (min-width: 0px) and (max-width: 720px) {
          #facebook { display: none; }
          .mobile-hide{ display: none; }
        }

    </style>
</head>

<body>

{% block content %}

{% endblock %}


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
        integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
        integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{{ url_for('static', filename='js/ie10-viewport-bug-workaround.js') }}"></script>
<script src="https://use.fontawesome.com/aae228be33.js"></script>

</body>
</html>

src/templates/home.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <div class="row justify-content-center">
    <img src="{{ url_for('static', filename='images/Rolling_Rock_logo.gif') }}" style="max-width:200px; max-height:200px; margin-top: -7px; margin-bottom: 10px">
    </div>
    <hr>
    <div class="row">
        <div class="col text-center">
            <h1>2018 Summer Schedule</h1>
        </div>
    </div>
    <div class="row header text-center">
        <div class="col-2 col-md-2"><strong>Date</strong></div>
        <div class="col-2 col-md-2"><strong>Time</strong></div>
        <div class="col-4 col-md-2"><strong>Venue</strong></div>
        <div class="col-md-2 mobile-hide"><strong>Home Team</strong></div>
        <div class="col-md-2 mobile-hide"><strong>Away Team</strong></div>
        <div class="col-2 col-md-1"></div>
    </div>
    {% for game in games %}
    <div class="row detail text-center">
        <div class="col-2 col-md-2">{{ game.date }}</div>
        <div class="col-2 col-md-2">{{ game.time }}</div>
        <div class="col-4 col-md-2">{{ game.venue }}</div>
        <div class="col-md-2 mobile-hide">{{ game.home_team }}</div>
        <div class="col-md-2 mobile-hide">{{ game.away_team }}</div>
        <div class="col-2 col-md-1">
            <a type="button" class="btn btn-success btn-sm" href="{{ url_for('attendance.view_game', game_id=game._id) }}">
                Attendance
            </a>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}